### ISSUE TITLE
Westwood .PAL palette

### ISSUE THREAD

**Issue by xan2622** [cyotek/Cyotek.Windows.Forms.ColorPicker#9] opened 2017-08-29 05:56 UTC
Hello.
First of all, thank you for creating this software. 

Here is my request:
I am a fan and player of (old) Command & Conquer games. The community is still very active and there are many people who create "mods" for these games. Yes, even in 2017. 😊 

Here are some websites/forums to prove that there are still many people who are interested in modding these games:
http://ppmsite.com > https://ppmforums.com
http://www.openra.net > http://www.sleipnirstuff.com/forum
http://cncnz.com > http://forums.cncnz.com
https://cncnet.org > https://forums.cncnet.org

Most of these games were developped by [Westwood Studios](https://en.wikipedia.org/wiki/Westwood_Studios), a game company which litteraly created the RTS (strategy) genre.

Why do I tell you all that? Well, because I think your software could be _really_ useful for modders.
These 2D games use .SHP and .VXL files for units/tanks/buildings. 

SHP files contain many frames (256 colors indexed images), used for the animations of these sprites. But to create .SHP files, palette files are needed: C&C games use **Westwood .PAL palette files**.

Tools used by modders:
- [XCC Tools](http://xhp.xwis.net), source code [here](https://sourceforge.net/projects/xccu/files/)
- [OS SHPBuilder](https://www.ppmsite.com/?go=shpbuilderinfo), source code: [here](http://svn.ppmsite.com/listing.php?repname=OS+SHP+Builder&path=%2FOS+SHP+Builder+3.3x%2F&#ae7b7a3ab328dc6bad5351c7ef6eb332d)
- [OS Palette Editor 1.21](http://www.ppmsite.com/downloads/OS_Palette_Editor_1.21.exe), source code included in the installer

Here is some documentation about this .PAL file format:
https://www.gamefaqs.com/pc/196957-command-and-conquer/faqs/1835 (2nd paragraph)
https://github.com/OpenRA/OpenRA/wiki/Palettes-and-Remaps

According to what one of the [OpenRA](http://www.openra.net/) developers told me:
> These palettes are standard vga palettes. They are a bucket of bytes that contain 6bit per channel brightness values which gets pushed directly to a block of memory on the graphics card.

You can download these palette files here: [LKOccallpal.zip](http://lko.ppmsite.com/Public/Tibweb/MappingTutorials/LKOccallpal.zip). I got them from this ppmforums [thread](https://ppmforums.com/viewtopic.php?t=33830).

And here is how OpenRA supports this file format (OpenRA is an open-source RTS game engine coded in C#):
https://github.com/OpenRA/OpenRA/blob/bleed/OpenRA.Game/Graphics/Palette.cs

That's why I ask you (if you agree, please say yes) to support Westwood .pal files in your software.

This "feature request" matters a lot to me because supporting this palette filetype will let modders convert .ACT/.ACO/.ASE/.GPL to Westwood .PAL files and vice versa.

**Comment by cyotek** [comment] 2017-08-29 17:13
Hello,

Thanks for the suggestion and thank you for taking the time to put together a list of helpful resources. I do have a long list of formats to add to our palette editing software (the palette serialisation in this particular repository is a bit out of date and is another outstanding task for me to sort out).

However, ideally I need raw palette files - it's probably out of scope of our editor software to extract the palettes from mix files and I doubt I'd be adding support for that at this point in time.

I do have Red Alert 2 installed locally from Origin - plenty of `mix` files, but no palettes. I downloaded the OpenRA setup and extracted that and found 3 `pal` files. I then adapted my existing RgbTriplets/AdobeColorTable codeto shift the bits of each byte as per the OpenRA class you linked and could successfully read those files, so there's no problem there. However, the 3 files (`jungle`, `snow` and `cursor`) are very similar to each other (only a few subtle changes to each (unless of course I've read them incorrectly!)) so ideally I'd need something completely different and with a reference image I can compare with.

The main issue is that this format is exactly the same as RGB triplets palettes also used by older games, so that if I had a Westwood palette and a triplets palette, you can't tell the difference. But loading a Westwood palette using the full 8 bits results in a very dark palette, and loading RGB triplets using only 6 bits results in a completely wrong palette. Therefore there's plenty of scope for confusing end users into thinking the software is broken if it guesses wrong.

I'm definitely not against the idea - the more the merrier, and the fact that it is identical to another format (with the exception of the bit shifting) means it's trivial to implement. The problem is that as there isn't a way of telling the two formats apart (as they are both have the same extension, and both have 768 bytes without a signature) then I'd have to have the UI prompt for which format to use. At least `act` files have a different extension and usually 3 extra bytes containing the number of used colors.

I'm going to log it on our internal tracker for looking into in a future update. As you can could see from the [roadmap](https://www.cyotek.com/cyotek-palette-editor/roadmap) I do plan to include a number of additional formats in the non-bugfix version of the software. (I don't have a date for this at the moment as I'm currently working on a whole bunch of other outstanding work).

If you wanted to save me some time, if you have any palette files you've extracted from the mix files you can attach to this issue (if possible with a corresponding image file as a reference to make sure my implementation is correct) that would be helpful.

Once again thanks for the detailed suggestion.

Regards;
Richard Moss

**Comment by x-a-n-a-x** [comment] 2017-08-29 18:14
Hi Richard, thank you for taking time to answer me.

> However, ideally I need raw palette files - it's probably out of scope of our editor software to extract the palettes from mix files and I doubt I'd be adding support for that at this point in time.

I wouldn't dare to ask you to support .mix files since they are out of the scope of your software. Btw, there are other tools to do that (XCC Tools).

---

>  I do have Red Alert 2 installed locally from Origin - plenty of mix files, but no palettes.

Afaik, palettes are contained in these .MIX files and to find them, you need to use tools to extract these .MIX fils and other tools to generate the palette from an indexed .SHP file.

---

> ... But loading a Westwood palette using the full 8 bits results in a very dark palette, and loading RGB triplets using only 6 bits results in a completely wrong palette...

Yes, I also noticed the "dark palettes" problem after loading a Westwood .PAL file in your editor.
I am sorry but I am not a developer and unfortunately, I can't help you fix this problem. 😞 

---

> I'm definitely not against the idea - the more the merrier, and the fact that it is identical to another format (with the exception of the bit shifting) means it's trivial to implement. 
> 
> I'm going to log it on our internal tracker for looking into in a future update. 

Thank you for adding Westwood .PAL onto your todo list. I really appreciate.

---

> As you can could see from the roadmap I do plan to include a number of additional formats in the non-bugfix version of the software

Have you checked this [documentation](http://www.selapa.net/swatches/colors/fileformats.php)? I think it has been written by the author of [SwatchBooker](http://www.selapa.net/swatchbooker/)

---

> If you wanted to save me some time, if you have any palette files you've extracted from the mix files you can attach to this issue (if possible with a corresponding image file as a reference to make sure my implementation is correct) that would be helpful.

You can download these palette files here: [LKOccallpal.zip](http://lko.ppmsite.com/Public/Tibweb/MappingTutorials/LKOccallpal.zip). I got them from this ppmforums [thread](https://ppmforums.com/viewtopic.php?t=33830).

Thank you.

**Comment by x-a-n-a-x** [comment] 2017-08-29 19:05
I have created screenshots of palettes (the most used one in C&C games). 
Saved as PNG files. Tell me if that can help you.

[palette_screenshots.zip](https://github.com/cyotek/Cyotek.Windows.Forms.ColorPicker/files/1261427/palette_screenshots.zip)

**Comment by cyotek** [comment] 2017-08-30 15:58
Thanks for the images - should be useful when I get onto this.

**Comment by cyotek** [comment] 2017-12-29 10:42
Hello,

The latest nightly builds of our [color palette editor](https://www.cyotek.com/cyotek-palette-editor) now support the 18-bit RGB VGA palette used by Westwood games (note that this is beta and therefore may be buggy). I've also published some [C# code](https://www.cyotek.com/blog/reading-and-writing-18-bit-rgb-vga-palette-pal-files-with-csharp) which describes the format and how to read/write from it.

I won't be adding support directly the color picker controls in this repository as it was a mistake to add any palette serialization formats to it in the first place (they've all been removed in the v2 branch).

I'm going to close this issue now as this is no longer relevant to the color picker controls. Hope you find either the updated software or the source code examples useful!

Regards;
Richard Moss

**Closed by cyotek** 2017-12-29 10:42 UTC
